const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');const root=path.resolve(__dirname,'..');
const scripts=[...fs.readFileSync(path.join(root,'index.html'),'utf8').matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]);scripts.forEach(x=>new vm.Script(x));
const els={};function el(id){return els[id]||={value:'',innerHTML:'',textContent:'',dataset:{},classList:{contains:()=>false,toggle:()=>false},addEventListener(){},setAttribute(){},getAttribute(){return null},querySelectorAll(){return []},querySelector(){return el('dummy')},getElementsByTagName(){return []},contains(){return false},focus(){},scrollIntoView(){}};}
let response=JSON.parse(fs.readFileSync(path.join(root,'data/snapshot.json')));let fetched=[];
const ctx={console,URL,Intl,Date,Set,Map,Number,JSON,Math,Array,Object,String,RegExp,parseInt,localStorage:{getItem:()=>null,setItem(){}},document:{getElementById:el,querySelectorAll:()=>[],addEventListener(){},body:el('body'),activeElement:null},window:{addEventListener(){}},location:{href:'https://demo.github.io/beyblade/',hash:'',protocol:'https:'},setTimeout:()=>0,clearTimeout(){},setInterval:()=>0,AbortController,fetch:async url=>{fetched.push(url);return {ok:true,text:async()=>JSON.stringify(response)}}};
(async()=>{vm.createContext(ctx);vm.runInContext(scripts[0],ctx);await new Promise(r=>setImmediate(r));assert.equal(ctx.SOURCE_MODE,'facebook');assert.equal(ctx.D.r.length,0);assert(fetched[0].startsWith('https://demo.github.io/beyblade/snapshot.json?'));assert(ctx.ONLINE_READY);const now=Date.now(),iso=days=>new Date(now-days*86400000).toISOString();
const p=(id,days,price)=>({group_name:'測試',post_url:`https://www.facebook.com/groups/1492428162434388/posts/${id}/`,published_at:iso(days+1),capture_method:'original_post',excerpt:'測試資料',listings:[{model:'UX-03',price_twd:price,status:'成交',kind:'整顆',condition:'二手',version:'',sold_at:iso(days),price_basis:'seller_confirmed_final',evidence_excerpt:'測試賣家最終成交價'}]});
response={schema_version:2,captured_at:iso(0),references:[],posts:[p('123',5,800),p('124',60,400)],collection:{status:'ok'}};await ctx.fetchLatestSnapshot();const mi=ctx.MIDX['UX-03'];assert.equal(ctx.summary(mi).n,1);assert.equal(ctx.summary(mi).p,800);assert.equal(ctx.collect([]).n,1);assert(ctx.lineHtml(ctx.D.r[0]).includes('價格佐證'));
const bad=structuredClone(response);delete bad.posts[0].listings[0].sold_at;assert.throws(()=>ctx.validateSnapshot(bad));ctx.fetch=async()=>{throw Error('network failed')};await ctx.fetchLatestSnapshot();assert.equal(ctx.D.r.length,2);assert(ctx.ONLINE_ERROR);console.log('PASS: shared URL/subpath, initial online mode, strict 30-day sales, required final-price evidence, failed-fetch preservation');})();
